<<<<<<< HEAD
name: Hank Quinlan, Horrible Cop
markdown: kramdown
=======
title: Fátima Castro Jul
markdown: kramdown
author:
 email: fatima@det.uvigo.es
 linkedin: fátima-castro-jul-3ab70b94
 github: https://github.com/Facj
 researchgate: Fatima_Castro_Jul
 scholar: https://scholar.google.es/citations?user=ygiLLLoAAAAJ&hl=en
 orcid: https://orcid.org/0000-0002-3063-486X
 mendeley: https://www.mendeley.com/profiles/ftima-castro-jul3/
>>>>>>> 0d8d720bd1d96f0ffe05a8cef558da2f87435c97
